ALTER TYPE "TravellerPricingCategory" RENAME VALUE 'UGANDAN' TO 'UGANDANS';
ALTER TYPE "TravellerPricingCategory" RENAME VALUE 'EAST_AFRICAN' TO 'EAST_AFRICANS';
ALTER TYPE "TravellerPricingCategory" RENAME VALUE 'NON_EAST_AFRICAN' TO 'FOREIGNERS';
ALTER TYPE "TravellerPricingCategory" ADD VALUE IF NOT EXISTS 'RESIDENT_FOREIGNERS' AFTER 'FOREIGNERS';

ALTER TABLE "Tour" RENAME COLUMN "nonEastAfricanAdults" TO "foreignersAdults";
ALTER TABLE "Tour" RENAME COLUMN "nonEastAfricanChildren" TO "foreignersChildren";
ALTER TABLE "Tour" ADD COLUMN IF NOT EXISTS "residentForeignersAdults" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Tour" ADD COLUMN IF NOT EXISTS "residentForeignersChildren" INTEGER NOT NULL DEFAULT 0;
